-- Exercicio 01
-- CREATE DATABASE
CREATE DATABASE DB_SA04_EX1;

-- CREATE TABELA CLIENTES (1)
 CREATE TABLE IF NOT EXISTS Clientes( --Criando tabela
ID INT NOT NULL PRIMARY KEY,
Nome VARCHAR(30) NOT NULL,
Sobrenome VARCHAR(30) NOT NULL,
Email VARCHAR (30) NOT NULL
);

-- SELECIONAR TABELA CLIENTES
SELECT *FROM Clientes;

-- ADICIONA RESTRIÇÃO NA TABELA PARA O EMAIL SER ÚNICO (2)
ALTER TABLE Clientes ADD CONSTRAINT Email UNIQUE (Email);

-- CRIAR TABELA PEDIDOS (3)
CREATE TABLE IF NOT EXISTS Pedidos(
    ID INT NOT NULL PRIMARY KEY,
    ID_Clientes INT NOT NULL,

    -- REFERENCIAR ID DA TABELA CLIENTES (4)
    FOREIGN KEY (ID_Clientes) REFERENCES CLIENTES (ID),
    DATA_PEDIDO VARCHAR (30) NOT NULL,
    TOTAL DECIMAL (10,3) NOT NULL
);

-- SELECIONAR TABELA PEDIDOS
SELECT *FROM Pedidos;

-- CRIAR COLUNA STATUS NA TABELA PEDIDOS (5)
ALTER TABLE Pedidos ADD COLUMN STATUS VARCHAR(30) CHECK (STATUS IN ('EM ANDAMENTO', 'FINALIZADO', 'CANCELADO'));

-- APAGRA TABELAS
DROP TABLE Clientes;
DROP TABLE Pedidos;

-- CRIAR AS TABELAS NOVAMENTE, AGORA COM SERIAL NO LUGAR DO INT
 CREATE TABLE IF NOT EXISTS Clientes( --Criando tabela
ID SERIAL PRIMARY KEY,
Nome VARCHAR(30) NOT NULL,
Sobrenome VARCHAR(30) NOT NULL,
Email VARCHAR (30) NOT NULL
);

ALTER TABLE Clientes ADD CONSTRAINT Email UNIQUE (Email);

CREATE TABLE IF NOT EXISTS Pedidos(
    ID SERIAL PRIMARY KEY,
    ID_Clientes INT NOT NULL,
    -- REFERENCIAR ID DA TABELA CLIENTES 
    FOREIGN KEY (ID_Clientes) REFERENCES CLIENTES (ID),
    DATA_PEDIDO VARCHAR (30) NOT NULL,
    TOTAL DECIMAL (10,2) NOT NULL
);

ALTER TABLE Pedidos ADD COLUMN STATUS VARCHAR(30) CHECK (STATUS IN ('EM ANDAMENTO', 'FINALIZADO', 'CANCELADO'));

-- DML
-- INSERIR DADOS DE TRÊS CLIENTES (1)
INSERT INTO Clientes (Nome, Sobrenome, Email) VALUES ('charles', 'leclerc', 'charles.leclerc@gmail.com');
INSERT INTO Clientes (Nome, Sobrenome, Email) VALUES ('marcos', 'verstappen', 'marcos.verstappen@gmail.com');
INSERT INTO Clientes (Nome, Sobrenome, Email) VALUES ('cassio', 'alves', 'cassio.alves@gmail.com');

SELECT *FROM Clientes;

INSERT INTO Pedidos (ID_Clientes, DATA_PEDIDO, TOTAL, STATUS) VALUES ('1', '2023-08-08', '112.99', 'FINALIZADO');
INSERT INTO Pedidos (ID_Clientes, DATA_PEDIDO, TOTAL, STATUS) VALUES ('2', '2023-09-08', '99.99', 'EM ANDAMENTO');
INSERT INTO Pedidos (ID_Clientes, DATA_PEDIDO, TOTAL, STATUS) VALUES ('3', '2023-10-08', '79.99', 'CANCELADO');
INSERT INTO Pedidos (ID_Clientes, DATA_PEDIDO, TOTAL, STATUS) VALUES ('2', '2024-03-03', '201.99', 'FINALIZADO');
INSERT INTO Pedidos (ID_Clientes, DATA_PEDIDO, TOTAL, STATUS) VALUES ('1', '2023-03-11', '89.99', 'CANCELADO');

SELECT *FROM Pedidos;

-- ATUALIZAR DADO DA COLUNA TOTAL
UPDATE Pedidos SET TOTAL = 137.38
WHERE ID = 4;
